package io.github.dr0idbot.vlucide.generator;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Scans Lucide SVG icon files from the local node_modules directory (installed
 * via npm / frontend-maven-plugin), then generates:
 * <ul>
 * <li>{@code LucideIcon.java} — an enum of all icons</li>
 * <li>SVG files under {@code META-INF/resources/lucide/}</li>
 * </ul>
 * <p>
 * Run from the project root:
 * 
 * <pre>{@code
 * mvn -pl lucide-icons-generator exec:java
 * }</pre>
 */
public class IconGenerator {

	private static final String GENERATED_HEADER = "/*\n"
			+ " * This file is auto-generated by the lucide-icons-generator module.\n"
			+ " * Do not edit by hand. Run `mvn -pl lucide-icons-generator exec:java` to regenerate.\n" + " */\n";

	private final Path runtimeResourcesDir;
	private final Path runtimeJavaDir;

	/**
	 * Constructor.
	 *
	 * @param runtimeResourcesDir path to {@code lucide-icons/src/main/resources}
	 * @param runtimeJavaDir      path to {@code lucide-icons/src/main/java}
	 */
	public IconGenerator(Path runtimeResourcesDir, Path runtimeJavaDir) {
		this.runtimeResourcesDir = runtimeResourcesDir;
		this.runtimeJavaDir = runtimeJavaDir;
	}

	public static void main(String[] args) throws Exception {
		Path projectRoot = findProjectRoot();
		Path resourcesDir = projectRoot.resolve("v-lucide-icons/src/main/resources");
		Path javaDir = projectRoot.resolve("v-lucide-icons/src/main/java");

		IconGenerator generator = new IconGenerator(resourcesDir, javaDir);
		generator.run();
	}

	/**
	 * Finds the project root by walking up from the working directory looking for
	 * the parent POM.
	 */
	static Path findProjectRoot() {
		Path current = Paths.get(".").toAbsolutePath().normalize();
		while (current != null) {
			if (Files.exists(current.resolve("pom.xml"))) {
				try {
					String content = Files.readString(current.resolve("pom.xml"));
					if (content.contains("<artifactId>vaadin-lucide-icons</artifactId>")) {
						return current;
					}
				} catch (IOException ignored) {
				}
			}
			current = current.getParent();
		}
		throw new IllegalStateException(
				"Could not find project root (containing parent POM with vaadin-lucide-icons-parent). "
						+ "Run from the project root directory.");
	}

	/**
	 * Runs the full generation pipeline.
	 */
	public void run() throws Exception {
		System.out.println("=== Lucide Icon Generator ===");

		Path iconsSrcDir = findProjectRoot().resolve("v-lucide-icons-generator/node_modules/lucide-static/icons");
		if (!Files.exists(iconsSrcDir)) {
			throw new IOException("Could not find icons directory. Make sure npm install was run first (expected at: "
					+ iconsSrcDir + ")");
		}

		System.out.println("Scanning icons directory: " + iconsSrcDir);
		List<String> iconNames;
		try (Stream<Path> paths = Files.list(iconsSrcDir)) {
			iconNames = paths.filter(p -> p.getFileName().toString().endsWith(".svg"))
					.map(p -> p.getFileName().toString().replace(".svg", "")).sorted().collect(Collectors.toList());
		}
		System.out.println("Found " + iconNames.size() + " icons.");

		Path svgTargetDir = runtimeResourcesDir.resolve("META-INF/resources/lucide");
		if (Files.exists(svgTargetDir)) {
			try (Stream<Path> existing = Files.list(svgTargetDir)) {
				existing.forEach(p -> {
					try {
						Files.deleteIfExists(p);
					} catch (IOException ignored) {
					}
				});
			}
		}
		Files.createDirectories(svgTargetDir);

		System.out.println("Processing and copying SVG files...");
		int processed = 0;
		for (String name : iconNames) {
			Path srcPath = iconsSrcDir.resolve(name + ".svg");
			Path targetPath = svgTargetDir.resolve(name + ".svg");
			try {
				String raw = Files.readString(srcPath, StandardCharsets.UTF_8);
				String normalized = normalizeSvg(raw);
				Files.writeString(targetPath, normalized, StandardCharsets.UTF_8);
				processed++;
			} catch (Exception e) {
				System.err.println("  WARN: failed to process '" + name + "': " + e.getMessage());
			}
		}
		System.out.println("SVGs: " + processed + " processed and written to target resources.");

		System.out.println("Generating LucideIcon.java...");
		generateEnum(iconNames);

		System.out.println("=== Done ===");
	}

	/**
	 * Normalizes SVG content for use with the {@code <vaadin-icon>} web component.
	 * <p>
	 * Normalization:
	 * <ul>
	 * <li>Strips XML declarations ({@code <?xml ...?>})</li>
	 * <li>Strips {@code width} and {@code height} attributes from the root
	 * {@code <svg>} element (the {@code <vaadin-icon>} web component controls
	 * sizing via CSS)</li>
	 * <li>Strips HTML comments</li>
	 * <li>Normalizes line endings to LF</li>
	 * </ul>
	 */
	static String normalizeSvg(String svg) {
		String result = svg;
		// Remove XML declaration (case-insensitive, optional whitespace/newlines)
		result = result.replaceAll("(?i)<\\?xml[^>]*\\?>", "").trim();

		// Remove width/height only from the root <svg> element.
		// The capture group (<svg\\b[^>]*?>) keeps the match inside the opening tag,
		// so child elements like <rect width=...> are never touched.
		result = result.replaceAll("(?i)(<svg\\b[^>]*?)\\s+width\\s*=\\s*['\"]?\\d+(?:\\.\\d+)?(?:px|em|%)?['\"]?", "$1 ");
		result = result.replaceAll("(?i)(<svg\\b[^>]*?)\\s+height\\s*=\\s*['\"]?\\d+(?:\\.\\d+)?(?:px|em|%)?['\"]?", "$1 ");

		// Remove HTML/XML comments
		result = result.replaceAll("(?i)<!--[\\s\\S]*?-->", "");

		// Normalize line endings
		result = result.replace("\r\n", "\n").replace("\r", "\n");
		return result.trim();
	}

	/**
	 * Generates the {@code LucideIcon.java} enum file.
	 */
	void generateEnum(List<String> iconNames) throws Exception {
		Path packageDir = runtimeJavaDir.resolve("io/github/dr0idbot/vlucide");
		Files.createDirectories(packageDir);
		Path enumFile = packageDir.resolve("LucideIcon.java");

		StringBuilder sb = new StringBuilder();
		sb.append("package io.github.dr0idbot.vlucide;\n\n");
		sb.append(GENERATED_HEADER);
		sb.append("\n");
		sb.append("/**\n");
		sb.append(" * Enum of all available Lucide icons.\n");
		sb.append(" * <p>\n");
		sb.append(" * Each constant corresponds to an icon in the Lucide icon set.\n");
		sb.append(" * Use {@link #create()} to obtain a {@link LucideSvgIcon} instance.\n");
		sb.append(" *\n");
		sb.append(" * @see <a href=\"https://lucide.dev\">Lucide</a>\n");
		sb.append(" */\n");
		sb.append("public enum LucideIcon {\n\n");

		// Enum constants
		for (int i = 0; i < iconNames.size(); i++) {
			String name = iconNames.get(i);
			String constantName = toEnumConstant(name);

			sb.append("    ").append(constantName).append("(\"").append(name).append("\")");
			if (i < iconNames.size() - 1) {
				sb.append(",");
			} else {
				sb.append(";");
			}
			sb.append("\n\n");
		}

		// Fields and constructor
		sb.append("    private final String iconName;\n\n");
		sb.append("    LucideIcon(String iconName) {\n");
		sb.append("        this.iconName = iconName;\n");
		sb.append("    }\n\n");

		// getIconName()
		sb.append("    /**\n");
		sb.append("     * Returns the Lucide icon file name (without {@code .svg} extension).\n");
		sb.append("     *\n");
		sb.append("     * @return the icon name in kebab-case\n");
		sb.append("     */\n");
		sb.append("    public String getIconName() {\n");
		sb.append("        return iconName;\n");
		sb.append("    }\n\n");

		// create()
		sb.append("    /**\n");
		sb.append("     * Creates a new {@link LucideSvgIcon} for this icon.\n");
		sb.append("     *\n");
		sb.append("     * @return a new icon component\n");
		sb.append("     */\n");
		sb.append("    public LucideSvgIcon create() {\n");
		sb.append("        return LucideIconFactory.create(iconName);\n");
		sb.append("    }\n");

		sb.append("}\n");

		Files.writeString(enumFile, sb.toString(), StandardCharsets.UTF_8);
		System.out.println("Wrote " + enumFile);
	}

	/**
	 * Converts a kebab-case icon name to a Java enum constant.
	 * <p>
	 * Examples:
	 * <ul>
	 * <li>{@code arrow-left} → {@code ARROW_LEFT}</li>
	 * <li>{@code user-round} → {@code USER_ROUND}</li>
	 * </ul>
	 */
	static String toEnumConstant(String kebabCase) {
		String result = kebabCase.replace("-", "_").toUpperCase(java.util.Locale.ROOT);
		if (result.matches("^\\d.*")) {
			result = "_" + result;
		}
		return result;
	}
}
